package com.mhr.blog.enums;

import org.springframework.security.core.GrantedAuthority;

public enum Authorities implements GrantedAuthority{

	OP_ACCESS_ADMIN,
	OP_ACCESS_USER,
	OP_NEW_USER,
	OP_EDIT_USER,
	OP_DELETE_USER,
	OP_DELETE_ALL_USER,
	OP_SHOW_ALL_USER,
	OP_SHOW_ONE_USER,
	OP_NEW_POST,
	OP_EDIT_POST,
	OP_DELETE_POST,
	OP_DELETE_ALL_POST,
	OP_SHOW_ONE_POST,
	OP_SHOW_ALL_POST,
	OP_NEW_CATEGORIES,
	OP_EDIT_CATEGORIES,
	OP_DELETE_CATEGORIES,
	OP_DELETE_ALL_CATEGORIES,
	OP_SHOW_ONE_CATEGORIES,
	OP_SHOW_ALL_CATEGORIES,
	OP_NEW_ROLE,
	OP_EDIT_ROLE,
	OP_SHOW_ONE_ROLE,
	OP_SHOW_ALL_ROLE,
	OP_DELETE_ROLE,
	OP_DELETE_ALL_ROLE,
	OP_NEW_COMMENT,
	OP_EDIT_COMMENT,
	OP_SHOW_ONE_COMMENT,
	OP_SHOW_ALL_COMMENT,
	OP_DELETE_ONE_COMMENT,
	OP_DELETE_ALL_COMMENT;
	

	@Override
	public String getAuthority() {
		return this.name();
	}
	
}
